package com.phantasosoneiroi.expenses_api;

import java.util.Date;

// import javax.persistence.Column;
// import javax.persistence.Entity;
// import javax.persistence.GeneratedValue;
// import javax.persistence.GenerationType;
// import javax.persistence.Id;
// import javax.persistence.Table;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// @Entity
// @Table(name = "expenses")
// @Data
// @AllArgsConstructor
// @NoArgsConstructor
@DynamoDBTable(tableName = "expenses")
public class ExpenseModel {
    
    // @Id
    // @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    // @DynamoDBAutoGeneratedKey
    private String expenseId;

    // @Column(name = "store")
    @DynamoDBAttribute
    private String store;

    // @Column(name = "address")
    @DynamoDBAttribute
    private String address;

    // @Column(name = "city")
    @DynamoDBAttribute
    private String city;

    // @Column(name = "state")
    @DynamoDBAttribute
    private String state;

    // @Column(name = "date")
    @DynamoDBAttribute
    private Date date;

    // @Column(name = "amount")
    @DynamoDBAttribute
    private Double amount;

    // @Column(name = "category")
    @DynamoDBAttribute
    private String category;

    public ExpenseModel() {

    }

    public ExpenseModel(String store, String address, String city, String state, Date date, Double amount, String category) {
        super();
        this.store = store;
        this.address = address;
        this.city = city;
        this.state = state;
        this.date = date;
        this.amount = amount;
        this.category = category;
    }

    @DynamoDBHashKey(attributeName = "expenseId")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.expenseId;
    }

    public void setId(String id) {
        this.expenseId = id;
    }

    public String getStore() {
        return this.store;
    }

    public void setStore(String store) {
        this.store = store;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

}
